import { User, Property, UserRole } from "./types";

export const MOCK_USERS: User[] = [
  {
    id: "renter_1",
    role: UserRole.RENTER,
    email: "chidi@email.com",
    phone: "+2348012345678",
    name: "Chidi Okonkwo",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Chidi",
    kycStatus: "verified",
    verified: true,
    createdAt: "2024-01-01T00:00:00Z",
    creditScore: 750,
    savedProperties: ["prop_1", "prop_3"],
  },
  {
    id: "landlord_1",
    role: UserRole.LANDLORD,
    email: "musa@email.com",
    phone: "+2348098765432",
    name: "Alhaji Musa Ibrahim",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Musa",
    kycStatus: "verified",
    verified: true,
    createdAt: "2024-01-01T00:00:00Z",
    creditScore: 800,
    savedProperties: [],
  },
  {
    id: "admin_1",
    role: UserRole.ADMIN,
    email: "admin@homesure.ng",
    phone: "+2348000000000",
    name: "Homesure Admin",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Admin",
    kycStatus: "verified",
    verified: true,
    createdAt: "2024-01-01T00:00:00Z",
    creditScore: 900,
    savedProperties: [],
  },
];

export const MOCK_PROPERTIES: Property[] = [
  {
    id: "prop_1",
    title: "Modern 2-Bedroom Apartment",
    description: "A beautifully finished 2-bedroom apartment in the heart of Yaba. Close to Unilag and major tech hubs.",
    price: 1200000,
    pricePeriod: "year",
    type: "flat",
    listingType: "rent",
    location: {
      address: "12 Hughes Avenue, Alagomeji, Yaba",
      city: "Lagos",
      state: "Lagos",
      lga: "Shomolu",
      coordinates: { lat: 6.505, lng: 3.377 },
    },
    details: {
      bedrooms: 2,
      bathrooms: 2,
      toilets: 3,
      parking: 2,
      yearBuilt: 2019,
      totalRooms: 4,
      furnishing: "semi-furnished",
    },
    amenities: ["24h Power", "Running Water", "AC", "Security", "Parking", "Internet"],
    images: [
      "https://picsum.photos/seed/h1/800/600",
      "https://picsum.photos/seed/h2/800/600",
      "https://picsum.photos/seed/h3/800/600",
    ],
    videoTour: null,
    verification: {
      status: "verified",
      verifiedAt: "2026-03-15T00:00:00Z",
      verifierId: "admin_1",
      notes: "Fully verified document and physical inspection.",
    },
    ownerId: "landlord_1",
    status: "active",
    views: 1234,
    inquiries: 45,
    createdAt: "2026-03-01T00:00:00Z",
    updatedAt: "2026-03-15T00:00:00Z",
  },
  {
    id: "prop_2",
    title: "Luxury 4-Bedroom Duplex",
    description: "Spacious duplex with modern finishing in a secured estate in Gwarinpa. Perfect for a growing family.",
    price: 45000000,
    pricePeriod: "sale",
    type: "duplex",
    listingType: "buy",
    location: {
      address: "5 Gwarinpa Road, Gwarinpa",
      city: "Abuja",
      state: "FCT",
      lga: "Municipal",
      coordinates: { lat: 9.1, lng: 7.4 },
    },
    details: {
      bedrooms: 4,
      bathrooms: 4,
      toilets: 5,
      parking: 4,
      yearBuilt: 2021,
      totalRooms: 6,
      furnishing: "furnished",
    },
    amenities: ["24h Power", "Running Water", "AC", "Security", "Parking", "Internet", "Swimming Pool", "Garden"],
    images: [
      "https://picsum.photos/seed/h4/800/600",
      "https://picsum.photos/seed/h5/800/600",
    ],
    videoTour: null,
    verification: {
      status: "verified",
      verifiedAt: "2026-03-10T00:00:00Z",
      verifierId: "admin_1",
      notes: "C of O verified.",
    },
    ownerId: "landlord_2",
    status: "active",
    views: 890,
    inquiries: 12,
    createdAt: "2026-03-05T00:00:00Z",
    updatedAt: "2026-03-10T00:00:00Z",
  },
  {
    id: "prop_3",
    title: "Cozy 1-Bedroom Flat",
    description: "Affordable and cozy 1-bedroom flat in a quiet neighborhood in Ibadan.",
    price: 800000,
    pricePeriod: "year",
    type: "flat",
    listingType: "rent",
    location: {
      address: "23 Ring Road, Ibadan",
      city: "Ibadan",
      state: "Oyo",
      lga: "Ibadan South-West",
      coordinates: { lat: 7.377, lng: 3.867 },
    },
    details: {
      bedrooms: 1,
      bathrooms: 1,
      toilets: 1,
      parking: 1,
      yearBuilt: 2015,
      totalRooms: 2,
      furnishing: "unfurnished",
    },
    amenities: ["Running Water", "Security"],
    images: [
      "https://picsum.photos/seed/h6/800/600",
    ],
    videoTour: null,
    verification: {
      status: "verified",
      verifiedAt: "2026-03-20T00:00:00Z",
      verifierId: "admin_1",
      notes: "Verified.",
    },
    ownerId: "landlord_3",
    status: "active",
    views: 456,
    inquiries: 8,
    createdAt: "2026-03-10T00:00:00Z",
    updatedAt: "2026-03-20T00:00:00Z",
  },
  // Add 9 more properties to reach 12
  ...Array.from({ length: 9 }).map((_, i) => ({
    id: `prop_${i + 4}`,
    title: `${["Elegant", "Stunning", "Modern", "Classic", "Spacious", "Gated", "Executive", "Serene", "Urban"][i]} ${["Apartment", "Terrace", "Penthouse", "Mansion", "Flat", "Cottage", "Office", "Studio", "Villa"][i]}`,
    description: "Experience premium living in one of Nigeria's top cities. This property features high-end finishes and excellent security.",
    price: Math.floor(Math.random() * (5000000 - 500000 + 1)) + 500000,
    pricePeriod: Math.random() > 0.5 ? "year" : "sale",
    type: "flat",
    listingType: Math.random() > 0.5 ? "rent" : "buy",
    location: {
      address: `${10 + i} Main Street, ${["Lekki", "Maitama", "GRA", "Banana Island", "Victoria Island", "Asokoro", "Magodo", "Ikoyi", "Festac"][i]}`,
      city: ["Lagos", "Abuja", "Port Harcourt", "Kano", "Ibadan"][Math.floor(Math.random() * 5)],
      state: ["Lagos", "FCT", "Rivers", "Kano", "Oyo"][Math.floor(Math.random() * 5)],
      lga: "LGA Name",
      coordinates: { lat: 6.5 + Math.random(), lng: 3.3 + Math.random() },
    },
    details: {
      bedrooms: Math.floor(Math.random() * 5) + 1,
      bathrooms: Math.floor(Math.random() * 5) + 1,
      toilets: Math.floor(Math.random() * 5) + 2,
      parking: Math.floor(Math.random() * 4) + 1,
      yearBuilt: 2010 + Math.floor(Math.random() * 14),
      totalRooms: 5,
      furnishing: "unfurnished",
    },
    amenities: ["Power", "Water", "Security"],
    images: [`https://picsum.photos/seed/prop${i+4}/800/600`],
    videoTour: null,
    verification: {
      status: "verified",
      verifiedAt: "2026-03-25T00:00:00Z",
      verifierId: "admin_1",
      notes: "Verified.",
    },
    ownerId: "landlord_1",
    status: "active",
    views: Math.floor(Math.random() * 2000),
    inquiries: Math.floor(Math.random() * 100),
    createdAt: "2026-03-20T00:00:00Z",
    updatedAt: "2026-03-25T00:00:00Z",
  })),
] as Property[];
